name: Deploy to Railway

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Java environment for Gradle
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Run Gradle build and tests
    - name: Build and Test with Gradle
      run: sh ./gradlew build test --info

    # Setup Node.js for Railway CLI
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install Railway CLI
    - name: Install Railway CLI
      run: |
        npm install -g @railway/cli

    # Deploy to Railway if tests pass
    - name: Deploy to Railway
      if: ${{ success() }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service students_crud_backend
